#!/bin/bash
# ----------------------------------------
# setup_printbox.sh
# Initializes PrintBoxOne environment
# ----------------------------------------

set -e

BASE_DIR="/home/lucas/printbox"

echo "[INFO] Creating directories under $BASE_DIR..."
mkdir -p "$BASE_DIR"

# -------------------------------
# Ask for credentials interactively
# -------------------------------
read -p "Enter Gmail address to use: " EMAIL_USER
read -s -p "Enter Gmail App Password: " EMAIL_APP_PASSWORD
echo
read -p "Enter printer name (check with 'lpstat -p -d'): " PRINTER_NAME
read -p "Enter SMTP server (default: smtp.gmail.com): " SMTP_SERVER
SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
read -p "Enter SMTP port (default: 587): " SMTP_PORT
SMTP_PORT=${SMTP_PORT:-587}

# -------------------------------
# Write config.py (secrets stay local!)
# -------------------------------
CONFIG_FILE="$BASE_DIR/config.py"
echo "[INFO] Writing config.py -> $CONFIG_FILE"
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by setup_printbox.sh
EMAIL_USER = "$EMAIL_USER"
EMAIL_APP_PASSWORD = "$EMAIL_APP_PASSWORD"

PRINTER_NAME = "$PRINTER_NAME"

SMTP_SERVER = "$SMTP_SERVER"
SMTP_PORT = $SMTP_PORT

# Paths for data storage
QUOTAS_FILE = "$BASE_DIR/quotas.json"
LOG_FILE = "$BASE_DIR/log.json"
WHITELIST_FILE = "$BASE_DIR/whitelist.json"

# Polling settings (future use)
POLL_INTERVAL_SEC = 300
RUN_CONTINUOUS_DEFAULT = False
EOF

# -------------------------------
# Initialize JSON files
# -------------------------------
echo "[INFO] Creating empty JSON DBs if missing..."

# Log file
if [ ! -f "$BASE_DIR/log.json" ]; then
  echo "[]" > "$BASE_DIR/log.json"
fi

# Whitelist file
if [ ! -f "$BASE_DIR/whitelist.json" ]; then
  echo "{}" > "$BASE_DIR/whitelist.json"
fi

# Quotas file → prefill with the EMAIL_USER
if [ ! -f "$BASE_DIR/quotas.json" ]; then
  cat > "$BASE_DIR/quotas.json" <<EOT
{
  "$EMAIL_USER": 500
}
EOT
fi

# -------------------------------
# Install dependencies
# -------------------------------
echo "[INFO] Installing Python + system dependencies..."
sudo apt-get update
sudo apt-get install -y python3-pip cups-bsd

echo "[INFO] Installing Python packages..."
python3 -m pip install --break-system-packages PyPDF2

echo "[INFO] Setup complete! 🎉"
echo "A config.py and JSON files have been created under $BASE_DIR"
echo "You can now test with:"
echo "  cd ~/PrintboxOne"
echo "  python3 admin_panel.py"
